# Row echelon and reduced


In [1]:
import numpy as np
def row_echelon_form(A):
    A = A.astype(float)
    rows, cols = A.shape
    r = 0
    for c in range(cols):
        pivot = np.argmax(abs(A[r:rows, c])) + r
        if A[pivot, c] == 0:
            continue
        A[[r, pivot]] = A[[pivot, r]]
        for i in range(r + 1, rows):
            factor = A[i, c] / A[r, c]
            A[i] = A[i] - factor * A[r]
        r += 1
        if r == rows:
            break
    return A
def rref(A):
    A = A.astype(float)
    rows, cols = A.shape
    lead = 0
    for r in range(rows):
        if lead >= cols:
            return A
        i = r
        while A[i, lead] == 0:
            i += 1
            if i == rows:
                i = r
                lead += 1
                if lead == cols:
                    return A
        A[[r, i]] = A[[i, r]]
        A[r] = A[r] / A[r, lead]
        for i in range(rows):
            if i != r:
                factor = A[i, lead]
                A[i] = A[i] - factor * A[r]
        lead += 1
    return A
A = np.array([
    [2, 1, -1, 8],
    [-3, -1, 2, -11],
    [-2, 1, 2, -3]
], dtype=float)
print("Original Matrix:\n", A)
REF = row_echelon_form(A.copy())
print("\nRow Echelon Form (REF):\n", REF)
RREF = rref(A.copy())
print("\nReduced Row Echelon Form (RREF):\n", RREF)


Original Matrix:
 [[  2.   1.  -1.   8.]
 [ -3.  -1.   2. -11.]
 [ -2.   1.   2.  -3.]]

Row Echelon Form (REF):
 [[ -3.          -1.           2.         -11.        ]
 [  0.           1.66666667   0.66666667   4.33333333]
 [  0.           0.           0.2         -0.2       ]]

Reduced Row Echelon Form (RREF):
 [[ 1.  0.  0.  2.]
 [ 0.  1.  0.  3.]
 [-0. -0.  1. -1.]]


# Cholesky Decomposition

In [2]:
import numpy as np
def cholesky_decomposition(A):
    n = A.shape[0]
    L = np.zeros((n, n))
    for i in range(n):
        for j in range(i + 1):
            sum_val = sum(L[i][k] * L[j][k] for k in range(j))
            if i == j:
                L[i][j] = np.sqrt(A[i][i] - sum_val)
            else:
                L[i][j] = (A[i][j] - sum_val) / L[j][j]
    return L
A = np.array([[25, 15, -5],
              [15, 18,  0],
              [-5,  0, 11]], float)
L = cholesky_decomposition(A)
print("Matrix A:\n", A)
print("\nCholesky Lower Triangular Matrix L:\n", L)
print("\nCheck: L * L^T =\n", L @ L.T)


Matrix A:
 [[25. 15. -5.]
 [15. 18.  0.]
 [-5.  0. 11.]]

Cholesky Lower Triangular Matrix L:
 [[ 5.  0.  0.]
 [ 3.  3.  0.]
 [-1.  1.  3.]]

Check: L * L^T =
 [[25. 15. -5.]
 [15. 18.  0.]
 [-5.  0. 11.]]
