In [11]:
import numpy 
arr = numpy.array([1,2,3,4,5])
print(arr)
print(arr.ndim)

[1 2 3 4 5]
1


### NUMPY

In [10]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)
print(np.__version__)
print(arr.ndim)

[1 2 3 4 5]
2.0.1
1


In [9]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
print(arr.ndim)

[[1 2 3]
 [4 5 6]]
2


In [25]:
arr = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr)
print(arr.ndim)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
3


In [8]:
arr = np.array([[[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]]])
print(arr)
print(arr.ndim)

[[[[1 2 3]
   [4 5 6]]

  [[1 2 3]
   [4 5 6]]

  [[1 2 3]
   [4 5 6]]]]
4


## slice


In [16]:
arr = np.array([1,2,3,4,5,6,7])
print(arr[1:5])

[2 3 4 5]


In [17]:
arr = np.array([1,2,3,4,5,6,7])
print(arr[::2])

[1 3 5 7]


#### 2D

In [22]:
import numpy as np
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[1,1:4])

[7 8 9]


In [23]:
print(arr[:4,:4])

[[1 2 3 4]
 [6 7 8 9]]


In [24]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr.reshape(-1))

[1 2 3 4 5 6]


In [28]:
arr1 = ([1,2,3,4,5])
arr2 =([6,7,8,9,10])
result =arr1 + arr2
print('concatenated array',result)

concatenated array [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [29]:
arr1 = ([[1,2,3],[4,5,6]])
arr2 = ([[7,8,9],[10,11,12]])
result =arr1 + arr2
print('concatenated array',result)

concatenated array [[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]
