In [4]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)
print(np.__version__)

[1 2 3 4 5]
2.3.2


In [6]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [8]:
import numpy as np
arr = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [12]:
import numpy as np
a = np.array(42)
b = np.array([1,2,3,4,5])
c = np.array([[1,2,3],[4,5,6]])
d = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [14]:
import numpy as np
arr = np.array([1,2,3,4], ndmin=5)
print(arr)
print('number of dimensions:', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions: 5


In [15]:
import numpy as np
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print('2nd element on 1st row:', arr[0,1])

2nd element on 1st row: 2


In [21]:
import numpy as np
arr = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
for x in np.nditer(arr):
 print(x)

1
2
3
4
5
6
7
8


In [22]:
import numpy as np
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr = np.concatenate((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


In [24]:
import numpy as np
arr = np.array([1,2,3,4,5,4,4])
x = np.where(arr==7)
print(x)

(array([], dtype=int64),)
